# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "firewire_ohci" "mptsas" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

#  fileSystems."/mnt/backup" =
#    { device = "/dev/disk/by-uuid/405afd75-0d2b-48f3-8c4f-b2250800ebf4";
#      fsType = "btrfs";
#      options = [ "compress=zstd" "nofail" ];
#    };

#  boot.initrd.luks.devices."backup".device = "/dev/disk/by-uuid/705d299c-1e67-472d-acb9-a970b8371eb8";

  fileSystems."/borgbackup" =
    { device = "/dev/disk/by-uuid/7df4581b-c1a4-4d6f-a16b-95b1b9a1f1c2";
      fsType = "btrfs";
      options = [ "compress=zstd" "nofail" ];
    };

  boot.initrd.luks.devices."borgbackup".device = "/dev/disk/by-uuid/d9a4ba4f-ff1f-4ab7-b59f-b59ebc7ed9a2";


  zramSwap = {
    algorithm = "zstd";
    enable = true;
    memoryPercent = 240;
  };


  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
